FROM isakfalk/mlss
# I am trying to reduce the size of the container
MAINTAINER Isak Falk (https://isakfalk.com)

WORKDIR "./environments/"

RUN git pull
RUN conda env create -f mlss_dl.yml
RUN git pull
RUN conda env create -f mlss_opt.yml
# Let's get freaky to solve Julia not being able to install Arpack properly

# Install julia
RUN /opt/conda/envs/mlss_opt/bin/julia -e 'using Pkg; ENV["python"] = "/opt/conda/envs/mlss_opt/bin/python"; Pkg.add("Distributions"); Pkg.add("SpecialFunctions"); Pkg.add("PyPlot");' \
    && /opt/conda/envs/mlss_opt/bin/julia -e "using Distributions; using SpecialFunctions; using PyPlot"

WORKDIR ".."

ENTRYPOINT ["sh", "/run.sh"]